# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=anotherpw
      - MYSQL_USER=user
      - MYSQL_DATABASE=dname

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080